<?php
add_action( 'vc_before_init', 'complex_vc_shortcodes' );

function complex_vc_shortcodes() {
	vc_add_params( 'vc_tta_tabs', array(
		
		array(
			'type' => 'dropdown',
			'holder' => 'div',
			'class' => '',
			'heading' => esc_html__( 'Tab layout', 'complex' ),
			'param_name' => 'tab_layout',
			'value' => array(
				esc_html__( 'Style 1', 'complex' ) => 'style_1',
				esc_html__( 'Style 2', 'complex' ) => 'style_2',
			),
			'group' => esc_html__( 'Complex Options', 'complex' ),
			'save_always' => true,
		),
		array(
			'type' => 'attach_image',
			'holder' => 'div',
			'class' => '',
			'heading' => esc_html__( 'Left banner', 'complex' ),
			'param_name' => 'left_banner',
			'value' => '',
			'group' => esc_html__( 'Complex Options', 'complex' ),
			'save_always' => true,
		),
	) );
	//Get menu by location
	vc_map( array(
		'name' => esc_html__( 'Menus', 'complex' ),
		'base' => 'menu_location',
		'class' => '',
		'category' => esc_html__( 'Complex Theme', 'complex'),
		'params' => array(
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Title', 'complex' ),
				'param_name' => 'title',
				'value' => '',
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Location', 'complex' ),
				'param_name' => 'location',
				'value' => array(
					array('value' => 'primary', 'label' => esc_html__( 'Primary Menu', 'complex' )),
					array('value' => 'categories', 'label' => esc_html__( 'Categories Menu', 'complex' )),
					array('value' => 'mobilemenu', 'label' => esc_html__( 'Mobile Menu', 'complex' ))
				)
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Limit first level items', 'complex' ),
				'param_name' => 'limit_items',
				'value' => '0',
				'description' => esc_html__( 'This option to display show more function to display full menu items. Set 0 for un-limit.', 'complex' )
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Extra class name', 'complex' ),
				'param_name' => 'el_class',
				'value' => '',
				'description' => esc_html__( 'If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.', 'complex' )
			)
		)
	) );
	//Brand logos
	vc_map( array(
		'name' => esc_html__( 'Brand Logos', 'complex' ),
		'base' => 'ourbrands',
		'class' => '',
		'category' => esc_html__( 'Complex Theme', 'complex'),
		'params' => array(
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Title', 'complex' ),
				'param_name' => 'title',
				'value' => '',
			),
			array(
				'type' => 'textarea',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Short description', 'complex' ),
				'param_name' => 'short_desc',
				'value' => '',
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Number of columns', 'complex' ),
				'param_name' => 'colsnumber',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
						'6'	=> '6',
					),
				'save_always' => true,
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Show on effect', 'complex' ),
				'param_name' => 'showon_effect',
				'value' => complex_get_effect_list(),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Number of rows', 'complex' ),
				'param_name' => 'rows',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Style', 'complex' ),
				'param_name' => 'style',
				'value' => array(
						esc_html__( 'Grid', 'complex' )	 	=> 'grid',
						esc_html__( 'Carousel', 'complex' ) 	=> 'carousel',
					),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Auto rotate', 'complex' ),
				'param_name' => 'autoplay',
				'value' => array(
					esc_html__( 'No', 'complex' ) 	=> 'false',
					esc_html__( 'Yes', 'complex' ) 	=> 'true',
				),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Play Timeout', 'complex' ),
				'param_name' => 'playtimeout',
				'value' => '5000',
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Rotate speed', 'complex' ),
				'param_name' => 'speed',
				'value' => '250',
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count desktop small', 'complex' ),
				'param_name' => 'desksmall',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count tablet', 'complex' ),
				'param_name' => 'tablet_count',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count tablet small', 'complex' ),
				'param_name' => 'tabletsmall',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count mobile', 'complex' ),
				'param_name' => 'mobile_count',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Margin', 'complex' ),
				'param_name' => 'margin',
				'value' => '30',
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Extra class name', 'complex' ),
				'param_name' => 'el_class',
				'value' => '',
				'description' => esc_html__( 'If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.', 'complex' )
			)
		)
	) );
	//Products Featured Categories
	vc_map( array(
		'name' => esc_html__( 'Products Featured Categories', 'complex' ),
		'base' => 'featuredcategories',
		'class' => '',
		'category' => esc_html__( 'Complex Theme', 'complex'),
		'params' => array(
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Title', 'complex' ),
				'param_name' => 'title',
				'value' => '',
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Number of category to show', 'complex' ),
				'param_name' => 'number',
				'value' => '10',
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Number of sub-categories', 'complex' ),
				'param_name' => 'sub_categories',
				'value' => '5',
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Show on effect', 'complex' ),
				'param_name' => 'showon_effect',
				'value' => complex_get_effect_list(),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Number of rows', 'complex' ),
				'param_name' => 'rows',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns', 'complex' ),
				'param_name' => 'columns',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
						'6'	=> '6',
					),
				'save_always' => true,
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count desktop small', 'complex' ),
				'param_name' => 'desksmall',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count tablet', 'complex' ),
				'param_name' => 'tablet_count',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count tablet small', 'complex' ),
				'param_name' => 'tabletsmall',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count mobile', 'complex' ),
				'param_name' => 'mobile_count',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Margin', 'complex' ),
				'param_name' => 'margin',
				'value' => '0',
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Extra class name', 'complex' ),
				'param_name' => 'el_class',
				'value' => '',
				'description' => esc_html__( 'If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.', 'complex' )
			)
		)
	) );
	//Specify Products
	vc_map( array(
		'name' => esc_html__( 'Specify Products', 'complex' ),
		'base' => 'specifyproducts',
		'class' => '',
		'category' => esc_html__( 'Complex Theme', 'complex'),
		'params' => array(
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Title', 'complex' ),
				'param_name' => 'title',
				'value' => '',
			),
			array(
				'type' => 'textarea',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Short description', 'complex' ),
				'param_name' => 'short_desc',
				'value' => '',
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Type', 'complex' ),
				'param_name' => 'type',
				'value' => array(
						esc_html__( 'Best Selling', 'complex' )		=> 'best_selling',
						esc_html__( 'Featured Products', 'complex' ) => 'featured_product',
						esc_html__( 'Top Rate', 'complex' ) 			=> 'top_rate',
						esc_html__( 'Recent Products', 'complex' ) 	=> 'recent_product',
						esc_html__( 'On Sale', 'complex' ) 			=> 'on_sale',
						esc_html__( 'Recent Review', 'complex' ) 	=> 'recent_review',
						esc_html__( 'Product Deals', 'complex' )		 => 'deals'
					),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Only In Category', 'complex' ),
				'param_name' => 'in_category',
				'value' => complex_get_all_taxonomy_terms('product_cat', true),
				'save_always' => true,
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Number of products to display', 'complex' ),
				'param_name' => 'number',
				'value' => '10',
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Style', 'complex' ),
				'param_name' => 'style',
				'value' => array(
						esc_html__( 'Grid', 'complex' )	 	=> 'grid',
						esc_html__( 'List', 'complex' ) 		=> 'list',
						esc_html__( 'Carousel', 'complex' ) 	=> 'carousel',
					),
				'save_always' => true,
			),
			array(
				 'type' => 'checkbox',
				 'heading' => esc_html__('Hide add to cart button','complex'),
				 'param_name' => 'hide_addcart',
				 'value' => array(
								'Yes' => true
							)
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Show on effect', 'complex' ),
				'param_name' => 'showon_effect',
				'value' => complex_get_effect_list(),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Item layout', 'complex' ),
				'param_name' => 'item_layout',
				'value' => array(
						esc_html__( 'Box', 'complex' ) 		=> 'box',
						esc_html__( 'List', 'complex' ) 	=> 'list',
						esc_html__( 'Simple List', 'complex' ) 	=> 'simple',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Number of rows', 'complex' ),
				'param_name' => 'rows',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Auto rotate', 'complex' ),
				'param_name' => 'autoplay',
				'value' => array(
					esc_html__( 'No', 'complex' ) 	=> 'false',
					esc_html__( 'Yes', 'complex' ) 	=> 'true',
				),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Play Timeout', 'complex' ),
				'param_name' => 'playtimeout',
				'value' => '5000',
				'group' => esc_html__( 'Carousel Options', 'complex' ),
				'save_always' => true,
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Rotate speed', 'complex' ),
				'param_name' => 'speed',
				'value' => '250',
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns', 'complex' ),
				'param_name' => 'columns',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count desktop small', 'complex' ),
				'param_name' => 'desksmall',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count tablet', 'complex' ),
				'param_name' => 'tablet_count',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count tablet small', 'complex' ),
				'param_name' => 'tabletsmall',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count mobile', 'complex' ),
				'param_name' => 'mobile_count',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Margin', 'complex' ),
				'param_name' => 'margin',
				'value' => '0',
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Extra class name', 'complex' ),
				'param_name' => 'el_class',
				'value' => '',
				'description' => esc_html__( 'If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.', 'complex' )
			)
		)
	) );
	//Products Category
	vc_map( array(
		'name' => esc_html__( 'Products Category', 'complex' ),
		'base' => 'productscategory',
		'class' => '',
		'category' => esc_html__( 'Complex Theme', 'complex'),
		'params' => array(
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Title', 'complex' ),
				'param_name' => 'title',
				'value' => '',
			),
			array(
				'type' => 'textarea',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Short description', 'complex' ),
				'param_name' => 'short_desc',
				'value' => '',
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Category', 'complex' ),
				'param_name' => 'category',
				'value' => complex_get_all_taxonomy_terms(),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Number of products to show', 'complex' ),
				'param_name' => 'number',
				'value' => '10',
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Style', 'complex' ),
				'param_name' => 'style',
				'value' => array(
						esc_html__( 'Grid', 'complex' )	 	=> 'grid',
						esc_html__( 'List', 'complex' ) 		=> 'list',
						esc_html__( 'Carousel', 'complex' ) 	=> 'carousel',
					),
			),
			array(
				 'type' => 'checkbox',
				 'heading' => esc_html__('Hide add to cart button','complex'),
				 'param_name' => 'hide_addcart',
				 'value' => array(
								'Yes' => true
							)
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns', 'complex' ),
				'param_name' => 'columns',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Show on effect', 'complex' ),
				'param_name' => 'showon_effect',
				'value' => complex_get_effect_list(),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Item layout', 'complex' ),
				'param_name' => 'item_layout',
				'value' => array(
						esc_html__( 'Box', 'complex' ) 		=> 'box',
						esc_html__( 'List', 'complex' ) 	=> 'list',
						esc_html__( 'Simple List', 'complex' ) 	=> 'simple',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Number of rows', 'complex' ),
				'param_name' => 'rows',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Auto rotate', 'complex' ),
				'param_name' => 'autoplay',
				'value' => array(
					esc_html__( 'No', 'complex' ) 	=> 'false',
					esc_html__( 'Yes', 'complex' ) 	=> 'true',
				),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Play Timeout', 'complex' ),
				'param_name' => 'playtimeout',
				'value' => '5000',
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Rotate speed', 'complex' ),
				'param_name' => 'speed',
				'value' => '250',
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count desktop small', 'complex' ),
				'param_name' => 'desksmall',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count tablet', 'complex' ),
				'param_name' => 'tablet_count',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count tablet small', 'complex' ),
				'param_name' => 'tabletsmall',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count mobile', 'complex' ),
				'param_name' => 'mobile_count',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Margin', 'complex' ),
				'param_name' => 'margin',
				'value' => '0',
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Extra class name', 'complex' ),
				'param_name' => 'el_class',
				'value' => '',
				'description' => esc_html__( 'If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.', 'complex' )
			)
		)
	) );
	
	//Testimonials
	vc_map( array(
		'name' => esc_html__( 'Complex Testimonials', 'complex' ),
		'base' => 'testimonials',
		'class' => '',
		'category' => esc_html__( 'Complex Theme', 'complex'),
		'params' => array(
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Title', 'complex' ),
				'param_name' => 'title',
				'value' => '',
			),
			array(
				'type' => 'textarea',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Short description', 'complex' ),
				'param_name' => 'short_desc',
				'value' => '',
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Number of products to show', 'complex' ),
				'param_name' => 'number',
				'value' => '10',
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Item Style', 'complex' ),
				'param_name' => 'item_style',
				'value' => array(
						esc_html__( 'Style 1', 'complex' ) 	=> '',
						esc_html__( 'Style 2', 'complex' ) 		=> 'style-2',
					),
				'save_always' => true,
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Style', 'complex' ),
				'param_name' => 'style',
				'value' => array(
						esc_html__( 'Carousel', 'complex' ) 	=> 'carousel',
						esc_html__( 'List', 'complex' ) 		=> 'list',
					),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Show on effect', 'complex' ),
				'param_name' => 'showon_effect',
				'value' => complex_get_effect_list(),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns', 'complex' ),
				'param_name' => 'columns',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Number of rows', 'complex' ),
				'param_name' => 'rows',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Auto rotate', 'complex' ),
				'param_name' => 'autoplay',
				'value' => array(
					esc_html__( 'Yes', 'complex' ) 	=> 'true',
					esc_html__( 'No', 'complex' ) 	=> 'false',
				),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Pagination', 'complex' ),
				'param_name' => 'pagination',
				'value' => array(
					esc_html__( 'Yes', 'complex' ) 	=> 'true',
					esc_html__( 'No', 'complex' ) 	=> 'false',
				),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Control Navigation', 'complex' ),
				'param_name' => 'control_nav',
				'value' => array(
					esc_html__( 'No', 'complex' ) 	=> 'false',
					esc_html__( 'Yes', 'complex' ) 	=> 'true',
				),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Play Timeout', 'complex' ),
				'param_name' => 'playtimeout',
				'value' => '5000',
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Rotate speed', 'complex' ),
				'param_name' => 'speed',
				'value' => '250',
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count desktop small', 'complex' ),
				'param_name' => 'desksmall',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count tablet', 'complex' ),
				'param_name' => 'tablet_count',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count tablet small', 'complex' ),
				'param_name' => 'tabletsmall',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count mobile', 'complex' ),
				'param_name' => 'mobile_count',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Margin', 'complex' ),
				'param_name' => 'margin',
				'value' => '0',
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Extra class name', 'complex' ),
				'param_name' => 'el_class',
				'value' => '',
				'description' => esc_html__( 'If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.', 'complex' )
			)
		)
	) );

	//Mail Chimp Newsletter Form
	vc_map( array(
		'name' => esc_html__( 'Newsletter Form (Mail Chimp)', 'complex' ),
		'base' => 'mailchimp_form',
		'class' => '',
		'category' => esc_html__( 'Complex Theme', 'complex'),
		'params' => array(
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Title', 'complex' ),
				'param_name' => 'title',
				'value' => '',
			),
			array(
				'type' => 'textarea',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Short description', 'complex' ),
				'param_name' => 'short_desc',
				'value' => '',
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Form ID', 'complex' ),
				'param_name' => 'id',
				'value' => '',
				'description' => esc_html__( 'Enter form ID here', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Extra class name', 'complex' ),
				'param_name' => 'el_class',
				'value' => '',
				'description' => esc_html__( 'If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.', 'complex' )
			)
		)
	) );
	
	//Feature content widget
	vc_map( array(
		'name' => esc_html__( 'Feature content', 'complex' ),
		'base' => 'featuredcontent',
		'class' => '',
		'category' => esc_html__( 'Complex Theme', 'complex'),
		'params' => array(
			array(
				'type' => 'iconpicker',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Icon', 'complex' ),
				'param_name' => 'icon',
				'value' => '',
			),
			array(
				'type' => 'textarea_raw_html',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Feature text', 'complex' ),
				'param_name' => 'feature_text',
				'value' => '',
			),
			array(
				'type' => 'textarea_raw_html',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Short description', 'complex' ),
				'param_name' => 'short_desc',
				'value' => '',
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Show on effect', 'complex' ),
				'param_name' => 'showon_effect',
				'value' => complex_get_effect_list(),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Extra class name', 'complex' ),
				'param_name' => 'el_class',
				'value' => '',
				'description' => esc_html__( 'If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.', 'complex' )
			)
		)
	) );
	
	//Latest posts
	vc_map( array(
		'name' => esc_html__( 'Blog posts', 'complex' ),
		'base' => 'blogposts',
		'class' => '',
		'category' => esc_html__( 'Complex Theme', 'complex'),
		'params' => array(
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Title', 'complex' ),
				'param_name' => 'title',
				'value' => '',
			),
			array(
				'type' => 'textarea',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Short description', 'complex' ),
				'param_name' => 'short_desc',
				'value' => '',
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Number of post to show', 'complex' ),
				'param_name' => 'number',
				'value' => '5',
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Style', 'complex' ),
				'param_name' => 'style',
				'value' => array(
						esc_html__( 'Carousel', 'complex' ) 	=> 'carousel',
						esc_html__( 'List', 'complex' ) 		=> 'list',
						esc_html__( 'Grid', 'complex' )	 	=> 'grid',
					),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns', 'complex' ),
				'param_name' => 'columns',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Show on effect', 'complex' ),
				'param_name' => 'showon_effect',
				'value' => complex_get_effect_list(),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Number of rows', 'complex' ),
				'param_name' => 'rows',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Auto rotate', 'complex' ),
				'param_name' => 'autoplay',
				'value' => array(
					esc_html__( 'No', 'complex' ) 	=> 'false',
					esc_html__( 'Yes', 'complex' ) 	=> 'true',
				),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Play Timeout', 'complex' ),
				'param_name' => 'playtimeout',
				'value' => '5000',
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Rotate speed', 'complex' ),
				'param_name' => 'speed',
				'value' => '250',
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Image scale', 'complex' ),
				'param_name' => 'image',
				'value' => array(
						esc_html__( 'Wide', 'complex' )	=> 'wide',
						esc_html__( 'Square', 'complex' ) => 'square',
					),
				'save_always' => true,
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Excerpt length', 'complex' ),
				'param_name' => 'length',
				'value' => '20',
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Readmore text', 'complex' ),
				'param_name' => 'readmore_text',
				'value' => 'Read more',
				'save_always' => true,
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Order by', 'complex' ),
				'param_name' => 'orderby',
				'value' => array(
						esc_html__( 'Posted Date', 'complex' )	=> 'date',
						esc_html__( 'Ordering', 'complex' ) => 'menu_order',
						esc_html__( 'Random', 'complex' ) => 'rand',
					),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Order Direction', 'complex' ),
				'param_name' => 'order',
				'value' => array(
						esc_html__( 'Descending', 'complex' )	=> 'DESC',
						esc_html__( 'Ascending', 'complex' ) => 'ASC',
					),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count desktop small', 'complex' ),
				'param_name' => 'desksmall',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count tablet', 'complex' ),
				'param_name' => 'tablet_count',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count tablet small', 'complex' ),
				'param_name' => 'tabletsmall',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'dropdown',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Columns count mobile', 'complex' ),
				'param_name' => 'mobile_count',
				'value' => array(
						'1'	=> '1',
						'2'	=> '2',
						'3'	=> '3',
						'4'	=> '4',
						'5'	=> '5',
					),
				'save_always' => true,
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Margin', 'complex' ),
				'param_name' => 'margin',
				'value' => '0',
				'group' => esc_html__( 'Carousel Options', 'complex' ),
			),
			array(
				'type' => 'textfield',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Extra class name', 'complex' ),
				'param_name' => 'el_class',
				'value' => '',
				'description' => esc_html__( 'If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.', 'complex' )
			)
		)
	) );
}
// Filter to replace default css class names for vc_row shortcode and vc_column
add_filter( 'vc_shortcodes_css_class', 'complex_custom_css_classes_for_vc_row_and_vc_column', 10, 2 );
function complex_custom_css_classes_for_vc_row_and_vc_column( $class_string, $tag ) {
  $class_string = preg_replace( '/vc_col-sm-(\d{1,2})/', 'col-sm-$1', $class_string ); // This will replace "vc_col-sm-%" with "my_col-sm-%"
  $class_string = str_replace('vc_column_container', 'column_container', $class_string);
  return $class_string; // Important: you should always return modified or original $class_string
}
?>